server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
    com.test: TRACE
spring:
  main:
    banner-mode: off
  application:
    name: Payment-Service

  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 500

  jpa:
    database: postgresql
    show_sql: true
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 25
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: secret
    driverClassName: org.postgresql.Driver

  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    mapper:
      accept-case-insensitive-enums: true
